use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LaneRuntime {
    Rootless,
    PrivilegedDev,
}

impl LaneRuntime {
    pub fn parse(s: &str) -> Result<Self, String> {
        match s.trim().to_lowercase().as_str() {
            "rootless" => Ok(Self::Rootless),
            "privileged-dev" | "privileged" | "dev" => Ok(Self::PrivilegedDev),
            other => Err(format!(
                "Unknown lane runtime '{other}'. Expected 'rootless' (default) or 'privileged-dev'."
            )),
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Rootless => "rootless",
            Self::PrivilegedDev => "privileged-dev",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ModelPreset {
    OpenCodeGo,
    Zen,
    Byok(String),
}

impl ModelPreset {
    pub fn parse(s: &str) -> Self {
        match s.trim().to_lowercase().as_str() {
            "opencode-go" | "go" => Self::OpenCodeGo,
            "zen" => Self::Zen,
            other => Self::Byok(other.to_string()),
        }
    }

    pub fn comment(&self) -> &'static str {
        match self {
            Self::OpenCodeGo => "# Model preset: OpenCode Go (subscription)",
            Self::Zen => "# Model preset: OpenCode Zen (pay-per-request)",
            Self::Byok(_) => "# Model preset: Bring Your Own Key",
        }
    }

    /// Base URL of the preset's `/models` probe endpoint. Used by the
    /// cockpit Providers live-ping and (once implemented) `studio init --ping`.
    pub fn default_base_url(&self) -> &'static str {
        match self {
            Self::OpenCodeGo => "https://go.opencode.ai/v1",
            Self::Zen => "https://zen.opencode.ai/v1",
            Self::Byok(_) => "<preset base URL>",
        }
    }

    /// Credential live-ping stub (issue #9). The CLI ships no HTTP client,
    /// so a real `/models` probe cannot run here yet — fail closed with an
    /// actionable error pointing at the Providers UI proof flow instead of
    /// ever claiming Connected-from-a-saved-string.
    pub fn live_ping_stub_error(&self) -> String {
        format!(
            "Credential live-ping is not implemented in `studio init` yet: \
             no HTTP probe ran against {}. \
             The key was NOT verified. Verify it in the cockpit Providers UI \
             (live /models ping proof) before relying on this .env.",
            self.default_base_url()
        )
    }
}

#[derive(Debug, Clone)]
pub struct InitConfig {
    pub repo_path: PathBuf,
    pub runtime: LaneRuntime,
    pub privileged_confirmed: bool,
    pub model_preset: ModelPreset,
    pub api_key: Option<String>,
}

pub struct EnvWriter;

impl EnvWriter {
    pub fn validate_and_render(config: &InitConfig) -> Result<String, String> {
        // Validate repo path exists
        if !config.repo_path.exists() {
            return Err(format!(
                "Repository path does not exist: {}",
                config.repo_path.display()
            ));
        }

        // Refuse privileged-dev without explicit confirmation
        if config.runtime == LaneRuntime::PrivilegedDev && !config.privileged_confirmed {
            return Err(
                "Refusing privileged-dev runtime without explicit typed confirmation. \
                 Privileged dev mounts host docker.sock into containers, conferring ROOT on the host. \
                 Use 'rootless' default or provide explicit confirmation."
                    .to_string(),
            );
        }

        let repo_canonical = config
            .repo_path
            .canonicalize()
            .unwrap_or_else(|_| config.repo_path.clone());

        let api_key_val = config.api_key.as_deref().unwrap_or("").trim();
        let credential_note = if api_key_val.is_empty() {
            "# credential: none provided (add OPENCODE_API_KEY later, then verify in Providers UI)."
        } else {
            "# credential: PRESENT but NOT live-pinged by the wizard — verify in Providers UI."
        };

        let doc = format!(
            r#"# STC environment. Generated by `studio init`.
# .env is gitignored and NEVER committed. Only .env.example is tracked.

# Lane runtime: rootless (default, secure) or privileged-dev (host socket mount).
STUDIO_LANE_RUNTIME={runtime}

# Invoking user, so lane-created files match host ownership.
HOST_UID=1000
HOST_GID=1000

# Repo checkout to bind into lanes.
STUDIO_REPO={repo}

# Harness versions pinned by the manager.
STUDIO_OPENCODE_VERSION=latest
STUDIO_PI_VERSION=latest

{preset_comment}
{credential_note}
OPENCODE_API_KEY={api_key}
"#,
            runtime = config.runtime.as_str(),
            repo = repo_canonical.display(),
            preset_comment = config.model_preset.comment(),
            credential_note = credential_note,
            api_key = api_key_val,
        );

        Ok(doc)
    }

    pub fn write_env_file(dest: &Path, content: &str, overwrite: bool) -> Result<(), String> {
        if dest.exists() && !overwrite {
            return Err(format!(
                "{} already exists. Pass --force to overwrite.",
                dest.display()
            ));
        }
        std::fs::write(dest, content)
            .map_err(|e| format!("Failed to write {}: {e}", dest.display()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn test_init_rootless_default_generates_valid_env() {
        let temp_dir = std::env::temp_dir().join(format!("stc_init_test_{}", std::process::id()));
        fs::create_dir_all(&temp_dir).unwrap();

        let config = InitConfig {
            repo_path: temp_dir.clone(),
            runtime: LaneRuntime::Rootless,
            privileged_confirmed: false,
            model_preset: ModelPreset::OpenCodeGo,
            api_key: Some("test_key_123".to_string()),
        };

        let rendered = EnvWriter::validate_and_render(&config).unwrap();
        assert!(rendered.contains("STUDIO_LANE_RUNTIME=rootless"));
        assert!(rendered.contains("OPENCODE_API_KEY=test_key_123"));
        assert!(rendered.contains("Model preset: OpenCode Go"));

        let env_file = temp_dir.join(".env");
        EnvWriter::write_env_file(&env_file, &rendered, false).unwrap();
        assert!(env_file.exists());

        // Overwrite without force fails
        let err = EnvWriter::write_env_file(&env_file, &rendered, false).unwrap_err();
        assert!(err.contains("already exists"));

        // Overwrite with force succeeds
        EnvWriter::write_env_file(&env_file, &rendered, true).unwrap();

        let _ = fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_init_refuses_privileged_dev_without_confirmation() {
        let temp_dir = std::env::temp_dir().join(format!("stc_priv_refuse_{}", std::process::id()));
        fs::create_dir_all(&temp_dir).unwrap();

        let config = InitConfig {
            repo_path: temp_dir.clone(),
            runtime: LaneRuntime::PrivilegedDev,
            privileged_confirmed: false,
            model_preset: ModelPreset::Zen,
            api_key: None,
        };

        let err = EnvWriter::validate_and_render(&config).unwrap_err();
        assert!(err.contains("Refusing privileged-dev runtime"));

        let _ = fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_init_accepts_privileged_dev_with_confirmation() {
        let temp_dir = std::env::temp_dir().join(format!("stc_priv_accept_{}", std::process::id()));
        fs::create_dir_all(&temp_dir).unwrap();

        let config = InitConfig {
            repo_path: temp_dir.clone(),
            runtime: LaneRuntime::PrivilegedDev,
            privileged_confirmed: true,
            model_preset: ModelPreset::Zen,
            api_key: Some("zen_key".to_string()),
        };

        let rendered = EnvWriter::validate_and_render(&config).unwrap();
        assert!(rendered.contains("STUDIO_LANE_RUNTIME=privileged-dev"));
        assert!(rendered.contains("OPENCODE_API_KEY=zen_key"));

        let _ = fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_init_rejects_nonexistent_repo_path() {
        let config = InitConfig {
            repo_path: PathBuf::from("/nonexistent/repo/path/stc_xyz_9999"),
            runtime: LaneRuntime::Rootless,
            privileged_confirmed: false,
            model_preset: ModelPreset::OpenCodeGo,
            api_key: None,
        };

        let err = EnvWriter::validate_and_render(&config).unwrap_err();
        assert!(err.contains("Repository path does not exist"));
    }

    #[test]
    fn test_init_stamps_not_pinged_note_when_key_present() {
        let temp_dir = std::env::temp_dir().join(format!("stc_ping_note_{}", std::process::id()));
        fs::create_dir_all(&temp_dir).unwrap();

        let config = InitConfig {
            repo_path: temp_dir.clone(),
            runtime: LaneRuntime::Rootless,
            privileged_confirmed: false,
            model_preset: ModelPreset::OpenCodeGo,
            api_key: Some("k".to_string()),
        };
        let rendered = EnvWriter::validate_and_render(&config).unwrap();
        assert!(rendered.contains("NOT live-pinged"));

        let _ = fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_live_ping_stub_fails_closed_with_actionable_error() {
        let err = ModelPreset::OpenCodeGo.live_ping_stub_error();
        assert!(err.contains("not implemented"));
        assert!(err.contains("Providers UI"));
        assert!(err.contains("NOT verified"));
    }
}
