// GENERATED by `cargo run -p studio-web --bin studio-web-gen-ts` — do not hand-edit.
// Source of truth: studio-web/src/api.rs (ts-rs 12.x, NOT the xazukx fork).
export type StalenessState = "Fresh" | "Stale" | "Lost";

export type StalenessDto = { state: StalenessState, label: string, db_age_ms: number, change_seq: number, };

export type TaskDto = { id: string, kind: string, status: string, lane: string, };

export type CountsDto = { building: number, validating: number, in_review: number, ready: number, };

export type StatusDto = { source: string, db_age_ms: number, staleness: StalenessDto, change_seq: number, counts: CountsDto, tasks: Array<TaskDto>, daemon_reachable: boolean, };

export type AskItemDto = { id: string, task_id: string, tool: string, status: string, reason: string | null, created_ms: number, decided_ms: number, decision_enabled: boolean, };

export type AskFeedDto = { source: string, decision_contract: string, items: Array<AskItemDto>, };

export type EventDto = { seq: number, tbl: string, row: string, op: string, old: string | null, new: string | null, };

export type GapKind = "None" | "Lost";

export type HistoryDto = { floor_seq: number, head_seq: number, gap: GapKind, events: Array<EventDto>, };

export type DaemonDto = { reachable: boolean, pid_file: string, version_file: string, pid: number | null, version: string | null, detail: string, };

export type HubDto = { floor_seq: number, head_seq: number, retained: number, cap: number, };

export type HealthDto = { version: string, db_path: string, db_ok: boolean, schema_version: number, daemon: DaemonDto, hub: HubDto, };

