// GENERATED by `cargo run -p studio-web --bin studio-web-gen-ts` — do not hand-edit.
// Source of truth: studio-web/src/api.rs (ts-rs 12.x, NOT the xazukx fork).
export type StalenessState = "Fresh" | "Stale" | "Lost";

export type StalenessDto = { state: StalenessState, label: string, db_age_ms: number, change_seq: number, };

export type TaskDto = { id: string, kind: string, status: string, lane: string, };

export type CountsDto = { building: number, validating: number, in_review: number, ready: number, };

export type StatusDto = { source: string, db_age_ms: number, staleness: StalenessDto, change_seq: number, counts: CountsDto, tasks: Array<TaskDto>, daemon_reachable: boolean, };

export type AskItemDto = { id: string, task_id: string, tool: string, status: string, reason: string | null, created_ms: number, decided_ms: number, decision_enabled: boolean, };

export type AskFeedDto = { source: string, decision_contract: string, items: Array<AskItemDto>, };

export type EventDto = { seq: number, tbl: string, row: string, op: string, old: string | null, new: string | null, };

export type GapKind = "None" | "Lost";

export type HistoryDto = { floor_seq: number, head_seq: number, gap: GapKind, events: Array<EventDto>, };

export type DaemonDto = { reachable: boolean, pid_file: string, version_file: string, pid: number | null, version: string | null, detail: string, };

export type HubDto = { floor_seq: number, head_seq: number, retained: number, cap: number, };

export type HealthDto = { version: string, db_path: string, db_ok: boolean, schema_version: number, daemon: DaemonDto, hub: HubDto, };

export type BucketDto = { name: string, order: number, tasks: Array<TaskDto>, };

export type NotificationDto = { id: string, task_id: string, tool: string, kind: string, label: string, };

export type WarRoomDto = { source: string, db_age_ms: number, staleness: StalenessDto, change_seq: number, buckets: Array<BucketDto>, notifications: Array<NotificationDto>, };

export type AgentEventDto = { seq: number, kind: string, provider: string, protocol_version: number, payload: string, ts_ms: number, refused: boolean, };

export type HookProviderDto = { name: string, protocol_version: number, compatible: boolean, };

export type AgentStreamDto = { source: string, db_age_ms: number, staleness: StalenessDto, change_seq: number, gap: GapKind, floor_seq: number, provider_protocol_version: number, providers: Array<HookProviderDto>, events: Array<AgentEventDto>, };

export type KanbanCardDto = { id: string, kind: string, status: string, evidence: Array<string>, };

export type KanbanColumnDto = { name: string, cards: Array<KanbanCardDto>, };

export type FeedbackDto = { id: string, task_id: string, head_sha: string, target_ref: string, tier: string, body: string, current_head: boolean, };

export type AuditDto = { source: string, db_age_ms: number, staleness: StalenessDto, change_seq: number, columns: Array<KanbanColumnDto>, feedback: Array<FeedbackDto>, };

export type ManifestSource = "Bundled" | "Remote" | "Override";

export type McpAgentDto = { name: string, manifest_source: ManifestSource, version: string, detected: boolean, explain: string, state: string, };

export type McpRegistryDto = { source: string, db_age_ms: number, staleness: StalenessDto, change_seq: number, agents: Array<McpAgentDto>, };

export type ProbeDto = { name: string, fresh: boolean, last_probe_ms: number, ttl_ms: number, detail: string, };

export type BudgetDto = { session: string, total: number, cache_hits: number, };

export type AuthProbeDto = { harness: string, method: string, status: string, detail: string, };

export type ProvidersDto = { source: string, db_age_ms: number, staleness: StalenessDto, change_seq: number, probes: Array<ProbeDto>, budgets: Array<BudgetDto>, lifetime_total: number, auth: Array<AuthProbeDto>, };

export type RunSlotDto = { slug: string, path: string, state: string, receipts: number, };

export type RunsDto = { source: string, db_age_ms: number, staleness: StalenessDto, change_seq: number, runs: Array<RunSlotDto>, deferred: string, };

export type DecideBody = { approved: boolean, reason: string, };

export type DecideOutcomeDto = { id: string, status: string, decided_ms: number, };

